apiVersion: v2
name: erigon
description: A Helm chart for Erigon Ethereum Execution Layer client
sources:
  - https://github.com/ledgerwatch/erigon
type: application
version: 7.0.0
appVersion: v2.39.0
maintainers:
  - name: kiln
    email: contact@kiln.fi
