apiVersion: v2
name: lighthouse-beacon
description: A Helm chart for Lighthouse Ethereum Beacon Chain client
sources:
  - https://github.com/sigp/lighthouse
type: application
version: 1.4.3
appVersion: "v2.0.1"
maintainers:
  - name: kiln
    email: contact@kiln.fi
